# Generated by Django 3.2.4 on 2021-06-25 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210623_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='count_In_Stock',
            new_name='countInStock',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='num_Reviews',
            new_name='numReviews',
        ),
    ]
