# Generated by Django 3.2.4 on 2021-07-11 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210625_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='countInStock',
            new_name='count_In_Stock',
        ),
    ]
